/**
 * Type declarations for PEG.js generated parser
 */

import type { Sequence } from './types.js';

/**
 * Parse meta-notation text into a sequence of blocks
 * Generated by PEG.js from meta.grammar.pegjs
 */
export function parse(input: string): Sequence;
